-- Table publique pour les commandes merch (vinyle, CD, t-shirts).
create table public.commandes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  items jsonb not null,
  nom text not null,
  email text not null,
  adresse text not null,
  montant numeric not null,
  statut text not null default 'nouvelle'
);

-- Écriture publique : n'importe quel visiteur peut passer commande.
create policy "Public can create commandes"
on public.commandes
for insert
with check (true);

-- Seuls les utilisateurs authentifiés peuvent consulter et gérer les commandes.
create policy "Authenticated users can view commandes"
on public.commandes
for select
using (auth.role() = 'authenticated');

create policy "Authenticated users can update commandes"
on public.commandes
for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Authenticated users can delete commandes"
on public.commandes
for delete
using (auth.role() = 'authenticated');

-- Active le RLS sur la table.
alter table public.commandes enable row level security;

-- Optionnel : index pour trier les commandes par date.
create index commandes_created_at_idx on public.commandes (created_at);
