-- Table publique pour les dates de concert.
create table public.concerts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date timestamptz not null,
  ville text not null,
  salle text not null,
  url_billetterie text null,
  complet boolean not null default false
);

-- Lecture publique : tout le monde peut voir les dates.
create policy "Public can view concerts"
on public.concerts
for select
using (true);

-- Seuls les utilisateurs authentifiés peuvent modifier la table.
create policy "Authenticated users can insert concerts"
on public.concerts
for insert
with check (auth.role() = 'authenticated');

create policy "Authenticated users can update concerts"
on public.concerts
for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Authenticated users can delete concerts"
on public.concerts
for delete
using (auth.role() = 'authenticated');

-- Active le RLS sur la table.
alter table public.concerts enable row level security;

-- Optionnel : index pour trier les concerts par date.
create index concerts_date_idx on public.concerts (date);
